### ISSUE TITLE
Test runner doesn't run worker tests properly

### ISSUE THREAD

**Issue by plehegar** [w3c/wpt-tools#129]
http://w3c-test.org/tools/runner/index.html
will attempt to run
 http://w3c-test.org/hr-time/basic.worker
instead of
 http://w3c-test.org/hr-time/basic.worker.html

**Comment by Ms2ger** [comment]
@youennf

**Comment by youennf** [comment]
Will look at it tomorrow

**Comment by Ms2ger** [comment]
FTR, caused by #126

**Comment by halindrome** [comment]
Actually, my PR is bogus.  If your system is trying to access "*.worker" it means the manifest is messed up.  Re-run the manifest generation and it should sort out.  

# ./manifest -r

I am going to withdraw that PR.

**Comment by youennf** [comment]
Fixing manifest generation at https://github.com/w3c/wpt-tools/pull/132

**Comment by gsnedders** [comment]
So, this is fixed?

**Comment by halindrome** [comment]
As far as I know this is fixed.  @plehegar should confirm though.

**Comment by plehegar** [comment]
[this is in progress but I'm having problems to run wptserve and no time to debug it :(]

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7199; please continue all discussion there.
