### ISSUE TITLE
Update html5lib

### ISSUE THREAD

**Issue by jdm** [w3c/wpt-tools#138]
It's out of date, and relying on python packages that are unmaintained.

**Comment by gsnedders** [comment]
I thought we wanted to keep the vendored packages stable for the sake of tests that rely on them (e.g., the WebDriver tests). @jgraham?

**Comment by jgraham** [comment]
I don't think the webdriver tests rely on html5lib.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7200; please continue all discussion there.
