### ISSUE TITLE
Fix the test runner

### ISSUE THREAD

**Issue by gsnedders** [w3c/wpt-tools#144]
After the manifest changes in #125 and #90 landed, the runner broke. We should fix this before updating the tools submodule in wpt.

**Comment by jeremypoulter** [comment]
I started having a look at this, but would be helpful if you could summarize what changed and what is the scope of the required fixes?

FYI so far I have fixed an issue with update_manifest.py not running.

**Comment by gsnedders** [comment]
There were a bunch of changes to the manifest format, so all the changes should essentially be handling of the JSON file in `runner.js` (along with the `update_manifest.py` changes which you've already done).

The big things are the dropping of `local_changes` (so all the JS code related to that can simply be killed!) and the change to each item being an object of path -> tests from being a list of tests. The `from_json` methods in `manifest/manifest.py` and `manifest/item.py` should be taken as the semantics of the JSON.

Really here the scope is to just get it working as well as it did before, and we're unlikely to require tests for this (because it's so much more of a pain to test and there's no infrastructure set up for tests for the runner yet!).

**Comment by jeremypoulter** [comment]
Thanks, I will have a look at this, FYI my working fork/branch is https://github.com/jeremypoulter/wpt-tools/tree/test_runner_fixes
