### ISSUE TITLE
gitignore filter only looks at the top of work tree

### ISSUE THREAD

**Issue by gsnedders** [w3c/wpt-tools#169]
However, we have a bunch more `gitignore` files in the tree:

```
./.gitignore
./annotation-model/annotations/.gitignore
./annotation-model/annotations/bodiesTargets/.gitignore
./annotation-model/collections/.gitignore
./annotation-model/definitions/.gitignore
./annotation-protocol/server/.gitignore
./annotation-vocab/tools/.gitignore
./cors/resources/.gitignore
./docs/.gitignore
./webaudio/.gitignore
```

**Comment by jgraham** [comment]
I am strongly in favour of fixing this by not having multiple gitignore files in the tree. It saves a considerable amount of work compared to checking for, and maybe reading, a `.gitignore` file in each subdirectory.

**Comment by gsnedders** [comment]
Really we probably want to pay attention to things that the specific user has ignored too, especially because IDE files often get ignored in `$XDG_CONFIG_HOME/git/ignore`/`$HOME/.config/git/ignore`. Meh.

**Comment by jgraham** [comment]
I mean a *short* static list of locations to check is fine. An `O(N)` list of locations that have to be examined as we walk the directory tree is less fine.

**Comment by gsnedders** [comment]
Those in annotation-model seem to be empty (i.e., zero byte files).

**Comment by gsnedders** [comment]
oh wow this is diabolical in my csswg-test working tree because I have thousands of files ignored in $GIT_DIR/info/excludes :(

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7206; please continue all discussion there.
