### ISSUE TITLE
Failure to run tests under /console

### ISSUE THREAD

**Issue by domfarolino** [w3c/wpt-tools#178]
I'm pretty new to WPT however I've recently contributed a couple tests to `/console` and at the time had no issue running tests in that directory. Unfortunately after some recent commits to `wpt-tools` and updating the submodule in WPT I can no longer run the tests in this directory. My error can be reproduced/locally fixed with the following steps:

1. Pull down latest from `web-platform-tests`. **Make sure** the `wpt-tools` submodule under `/tools` us up to date.
2. Run `./serve`
3. Nav to `http://web-platform.test:8000/tools/runner/index.html`
4. In the text box type `/console`
5. Click `start`
6. The freshly opened window should contain the following JSON when the tests fail to run:

```
{
    error: {
        message: "Traceback (most recent call last): File "/Users/domfarolino/Desktop/Git/web-platform-tests/tools/wptserve/wptserve/handlers.py", line 246, in __call__ rv = self.func(request, response) File "/Users/domfarolino/Desktop/Git/web-platform-tests/tools/serve/serve.py", line 83, in handle_request meta = "\n".join(self._get_meta(request)) File "/Users/domfarolino/Desktop/Git/web-platform-tests/tools/serve/serve.py", line 104, in _get_meta for key, value in read_script_metadata(f): TypeError: read_script_metadata() takes exactly 2 arguments (1 given) ",
        code: 500
    }
}
```

The same trace should also appear in the terminal.

I can fix this locally by manually checking out any commit before be66d1d99d4aef09c894003e3843073c74eeefc1 in the tools directory. 96948daeb47b7df41b72c5859970ff68da7dfbf0 works for example. Checking out be66d1d99d4aef09c894003e3843073c74eeefc1 or anything more recent breaks causes this error.

I'm assuming either the tests in `/console` are malformed (?) or a breaking change has been introduced in be66d1d99d4aef09c894003e3843073c74eeefc1. I noticed in the commit (https://github.com/w3c/wpt-tools/commit/be66d1d99d4aef09c894003e3843073c74eeefc1#diff-a4a16972d6eb6bd50611d4b024d296fbL341) the logic that handles tests ending with `.any.js` changes, and the tests under console end with `.any.js` so I'm wondering if this could be the culprit?

**Comment by annevk** [comment]
Try running:
```
git reset --HARD origin/master
git submodule update --init --recursive
```
Submodules often end up creating issues. I believe we're getting rid of them, but for now you'll hit that every now and then unfortunately.

It can also help rebasing outstanding PRs if you run into this.

**Comment by jgraham** [comment]
This is a bug. I made a fix. Seems like none of my usual reviewers are around today, so it may have to wait. Or I could coerce MikeSmith.

**Comment by gsnedders** [comment]
@jgraham can you update the submodule in wpt?

**Comment by domfarolino** [comment]
All good thanks!
