### ISSUE TITLE
Manifest feature request: for tests that could be manual or reftest, support a preference for reftests

### ISSUE THREAD

**Issue by qyearsley** [w3c/wpt-tools#196]
For example the test [css/css-writing-modes-3/background-position-vrl-018.xht](https://github.com/w3c/web-platform-tests/blob/master/css/css-writing-modes-3/background-position-vrl-018.xht) contains the following:
```html
  <link rel="match" href="background-position-vrl-018-ref.xht" />

  <meta content="image interact" name="flags" />
```

Because of the "interact" flag, the manifest generator now considers this to be a manual test, even though it could also be a reference test.

Might we want to change the behavior of the manifest to treat this as a reftest, or provide an option to treat it as a reftest?

Changing it to always treat such tests as reftests when possible would be an easy, simple change; it would just involve changing the order of the elif blocks at [SourceFile.manifest_items](https://github.com/w3c/wpt-tools/blob/master/manifest/sourcefile.py#L528)

More context: http://crbug.com/706953

**Comment by mrego** [comment]
We should find a way to fix this as it's making harder to import tests and run them automatically into Blink.

If the suggestion from @qyearsley is not good enough. Another option would be to fix the tests by changing the flags removing `interact` when it's not really mandatory.
From the [doc](http://web-platform-tests.org/writing-tests/css-metadata.html) (dunno if `interact` has some other meaning):
> interact: Requires human interaction (such as for testing scrolling behavior)

For example, in some tests that require focus we've a small JavaScript that focus the element, but we still have them marked as `interact`: [css/selectors4/focus-within-001.html](https://github.com/w3c/web-platform-tests/blob/master/css/selectors4/focus-within-001.html)
But *human interaction* is not required to run these tests. Only in the case that you don't have JavaScript support, then *human interaction* would be needed. But is this something we want to consider yet?

Pinging some people with more experience on CSS test suite to check what they think about this: @fantasai, @frivoal, @gsnedders. Thanks!
