### ISSUE TITLE
Update lint tool to check for comma or whitespace in test names

### ISSUE THREAD

**Issue by hrj** [w3c/wpt-tools#26]
When #25 is merged, the lint tool can ensure that comma or whitespace is not present in test names.

( I took a stab at it, but I am not very fluent in python. :soccer: pass. )

**Comment by sideshowbarker** [comment]
Thanks for raising this issue—I'll add the check for no spaces or commas in file paths to the lint tool myself (if @jgraham doesn't beat me to it). (And thanks also for the #25 patch—it's great to have that.)

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7189; please continue all discussion there.
