### ISSUE TITLE
Add a lint for broken links in link rel=match/mismatch

### ISSUE THREAD

**Issue by Ms2ger** [w3c/wpt-tools#28]
Not sure how hard this would be, but I submitted tests to csswg-test yesterday where I typoed the file name of the reference; it'd be useful for our lint to catch such mistakes.

**Comment by gsnedders** [comment]
I think the only complicating matter here is `.sub`.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7190; please continue all discussion there.
