### ISSUE TITLE
Allow the lint's `main` function to take an iterator

### ISSUE THREAD

**Issue by Wafflespeanut** [w3c/wpt-tools#45]
Currently, the `main` function takes no arguments, since [it makes use of `iter_files` directly](https://github.com/w3c/wpt-tools/blob/1d99b1e6a9468ed34afabc62e5606adc880a7e50/lint/lint.py#L253). It would be nice if it takes that iterator as an argument, so that we can pass custom file iterators to the main function (which would be helpful, because sometimes, we don't wanna check all the files).

cc @jgraham @Ms2ger

**Comment by Wafflespeanut** [comment]
(sigh)

**Comment by Ms2ger** [comment]
Fixed by #49.
