### ISSUE TITLE
w3c-test.org runner's "Show Reference" button is broken

### ISSUE THREAD

**Issue by zqzhang** [w3c/wpt-tools#47]
Moved from https://github.com/w3c/test-results/issues/19 by @cvrebert.

Whenever I click the "Show Reference" button for a reftest, the pop-up window is navigated to `http://w3c-test.orgundefined/` instead of to the reference webpage for the reftest.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7192; please continue all discussion there.
