### ISSUE TITLE
w3c-test.org runner thinks reftests should always compare unequal

### ISSUE THREAD

**Issue by zqzhang** [w3c/wpt-tools#48]
Moved from https://github.com/w3c/test-results/issues/20 by @cvrebert

The dialog box for reftests seems to say

> Test and ref should compare **unequal**

even when the reftest in question uses `rel="match"` instead of `rel="mismatch"`.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7193; please continue all discussion there.
