### ISSUE TITLE
Navbar Title is basically invisible (on chrome at least)

### ISSUE THREAD

**Issue by halindrome** [w3c/wpt-tools#80]
The font / color of the text is the same as the background or something...

![screenshot 2016-06-12 at 11 12 14](https://cloud.githubusercontent.com/assets/520688/15992277/a4cd16ee-308e-11e6-80d1-84867165f6f8.png)

**Comment by halindrome** [comment]
Actually it is just that the image is not set to float to the left.  I will put it in a patch I am putting together now.

**Comment by wpt-issue-mover** [comment]
This issue has been moved to https://github.com/w3c/web-platform-tests/issues/7197; please continue all discussion there.
